version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    restart: always

  client:
    build: ./client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    restart: always
