apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: basic-app
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://devops-test:qYqcOYe3rCSs0qy1@test-mongo-cloud.o8vsvyr.mongodb.net/devops_test?appName=test-mongo-cloud"
  API_KEY: "api-key-test-12345"
